#!/usr/bin/env php
<?php

require 'vendor/autoload.php';

use App\ParsePublicMethods;
use Symfony\Component\Console\Application;

$app = new Application('cli', 1.0);

$app->add(new ParsePublicMethods());

$app->run();